### ISSUE TITLE
Optionally replace an existing index upon creation if the index has changed

### ISSUE THREAD

**Issue by guyroyse** [redis/redis-om-node#12]
Right now, calls to `.createIndex` will fail if the index already exists. Change this to check for a matching index exists, and only rebuild if it doesn't match. Make this behavior opt-in based on a flag passed to `.createIndex`.

**Comment by Lionardo** [comment]
Another option would be to add a method like this:

```repository.listIndex();```

similar to JSON types
**FT._LIST**

**Comment by guyroyse** [comment]
That's an interesting idea. I need to think about it. Not sure it goes on `Repository` as repositories are bound to a particular schema. Might go on the `Client`.

I still want to make `.createIndex` smarter. The plan is to take the schema information needed to make the index and to generate a hash from it that is stored in Redis. Then, before attempting to create the index, see if it exists. If it does, compare the hashes. If they are different, rebuild the index.

**Comment by guyroyse** [comment]
Added to 0.2.0.
