### ISSUE TITLE
readme document mistakes

### ISSUE THREAD

**Issue by JiaJiaJiang** [redis/redis-om-node#122]
1. The `.search()` method becomes a property from chapter [Chaining Searches](https://github.com/redis/redis-om-node#chaining-searches) to the end of the readme file.
2. The 2nd code block in [Chaining Searches](https://github.com/redis/redis-om-node#chaining-searches) may has an error, `.return.all()` should be at the end of the search chain.

**Comment by colemilne54** [comment]
Number 1 is now fixed by this [PR](https://github.com/redis/redis-om-node/pull/185)

**Comment by guyroyse** [comment]
Fixed by #189.
