### ISSUE TITLE
Cannot search result with a value contains "|"

### ISSUE THREAD

**Issue by JiaJiaJiang** [redis/redis-om-node#124]
When the value in json contains "|" character, the value would not be found, only searching for the part before "|" can return it.

**Comment by guyroyse** [comment]
This has to do with how RediSearch indexes TAG fields. TAG fields are delimited by something, even if there is only a single value in them. The default is a comma. Redis OM overrides that to something a little less common, the pipe. You can change the default separator when you define you field in the Schema to be something else that you don't expect to be in your data like this:

```javascript
class Album extends Entity {}

const schema = new Schema(Album, {
  artist: { type: 'string', separator: ':' },
  title: { type: 'text' },
  year: { type: 'number' }
});
```

Note that the separator must be a single character. Multi-character separators are not permitted by RediSearch.
