### ISSUE TITLE
is INCRBY possible by using redis-om for the counter  update?

### ISSUE THREAD

**Issue by shashijangir** [redis/redis-om-node#127]
I am face some issue to update counter in redis-om. I use .save() to update data but multiple request is coming on same time and this counter value is 
not work properly. This is doing count only 1 if multple request is serving on same time.

               let mcData = await matchContestRepository.search()
                .where('contest_id').equals(contest_id)
                .and('match_id').equals(match_id).return.all() 

                mcData[0].joined_users += 1;
                let resposeData = await matchContestRepository.save(mcData[0]);

Can you suggest me how to implement this increment in redis-om for multiple request on same time.

**Comment by guyroyse** [comment]
Redis OM doesn't have this capability. Might be an interesting future enhancement. You can use the Node Redis client directly to do this, assuming you know the key name of the thing you want to update. The Entity has a `.keyName` property on it that contains the keyname.

```javascript
import { createClient } from 'redis'
import { Client } from 'redis-om'

/* use a Node Redis client instead of allowing Redis Om to create it */
const redis = createClient('redis://localhost:6379')
await redis.connect()
const client = await new Client().use(redis)

/* get the keyname *. */
const mcData = await matchContestRepository.search()
  .where('contest_id').equals(contest_id)
  .and('match_id').equals(match_id).return.all()

const keyName = mcData[0].keyName

/* update if you are using HASH */
await redis.hIncrBy(keyName, 'joined_users', 1)

/* update if you are using JSON */
await redis.json.numIncrBy(keyName, '$.joined_users', 1)
```

I haven't tested this code, of course, so it might have a bug in it, but the approach is correct.
