### ISSUE TITLE
on return.page() there seems to be a hardcoded value of 10k for offset, can this be raised?

### ISSUE THREAD

**Issue by exangel67** [redis/redis-om-node#129]
It seems I'm not able to use the return.page(offset, count) feature for a schema that has more than 10k records. Is this a hardcoded limit that can be changed? Thank you

**Comment by guyroyse** [comment]
This is a feature of RediSearch. If you'd like to change the maximum number of search results, you'll need to do it on your server settings. Details can be found [here](https://redis.io/docs/stack/search/configuring/).

**Comment by hursey013** [comment]
Running into this as well - if I try to set the offset above 10000 I do not get any results, for example:
```
await repo.search().return.page(10000, 1000)
```
Is this what you mean by maximum number of search results? Or does this mean that only up to 10,000 items will be indexed by default?

**Comment by hursey013** [comment]
Related https://github.com/RediSearch/RediSearch/pull/2804

**Comment by guyroyse** [comment]
Everything is indexed. It's the max number of results. RediSearch will not return more than the value set in [MAXSEARCHRESULTS](https://redis.io/docs/stack/search/configuring/#maxsearchresults). The docs say this is 1,000,000 but I think that's a typo as it's 10,000 in practice. Regardless, this is part of RediSearch, not Redis OM. Information on how to configure RediSearch can be found [here](https://redis.io/docs/stack/search/configuring/).

Also, you might want to note the [TIMEOUT](https://redis.io/docs/stack/search/configuring/#timeout) and [ON_TIMEOUT](https://redis.io/docs/stack/search/configuring/#on_timeout) settings as well. If you have a lot of results, you can run into the default 500ms timeout. But the timeout doesn't fail, it just returns what it has found so far. These settings let you change that behavior.

**Comment by ChrisTolmeijer** [comment]
Does this mean that for redis-om to be able to reach results 10,000 to 10,100 (which is 100 results total), the MAXSEARCHRESULTS setting needs to be at least 10.1k or above? Or in other words, redis-om is requesting the full 10.1k resultset and shaving off the offset in javascript? I'm trying to loop through my full 70k index with 50 results per page but running into the 10k limit at `.page(10000, 50)`.

**Comment by guyroyse** [comment]
That is exactly correct @ChrisTolmeijer.

**Comment by guyroyse** [comment]
Well, not exactly correct. Redis OM is requesting results from 10,000 to 10,050. RediSearch just won't provide them with configuration changes.

**Comment by ChrisTolmeijer** [comment]
Thank you for explaining. I just increased it on runtime with:
`FT.CONFIG SET MAXSEARCHRESULTS <value>`
