### ISSUE TITLE
matchExact methods break redis-parser when common search term automatically ignored by redis-search

### ISSUE THREAD

**Issue by jamesastound** [redis/redis-om-node#13]
As noted on the README.md [Full Text Search](https://github.com/redis/redis-om-node#full-text-search), "Full-text search is pretty clever. It understands that certain words (like a, an, or the) are common and ignores them." If the resulting search term reduces the term-count to one or fewer, redis-parser will throw an error. 

Example:  `await repository.search().where("MyData").matchExact("to Home").count();`

redis-search will remove "to", because it is common, leaving just "Home." This only leaves one search term when redis-parser is expecting 2 or more.

```JAVASCRIPT
UnhandledPromiseRejectionWarning: ReplyError: Syntax error at offset 9 near to
    at parseError (/<test>/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/<test>/node_modules/redis-parser/lib/parser.js:302:14)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(node:25411) ReplyError: Syntax error at offset 9 near to
    at parseError (/<test>/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/<test>/node_modules/redis-parser/lib/parser.js:302:14)
(node:25411) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```

This appears to affect all phrase methods in full text search. These methods should probably default to .match() if the filtered search terms are fewer than two.  Thanks.

EDIT: I guess, if the desired result, in my example, is the phrase "to Home", just providing results for "Home" would not be valid. So maybe there's a way to force redis-search to not ignore in these cases.

redis-parser: 3.0.0
redis-om-node: 0.1.3

**Comment by guyroyse** [comment]
Sounds like a bug. I'll look into it.

**Comment by guyroyse** [comment]
There's no direct way to solve this as exact match queries are not permitted with RediSearch. I improved the error message and added the capability to disable and change stop words. Let me know if you have any further problems but that should allow you to resolve the issue one way or another.

**Comment by jamesastound** [comment]
Hey, this is great. This should be sufficient for my testing needs. Great project, BTW. I love where this is heading. Look forward to it becoming a full fledged release product.
