### ISSUE TITLE
Can a schema reference another schema?

### ISSUE THREAD

**Issue by dingshukai** [redis/redis-om-node#133]
Complex entities may have deep fields and objects. 
I wish Schema (or Entity)  can be referenced by others.
currently field types in schema are only simple types like string, text, or date.

**Comment by guyroyse** [comment]
This has been asked multiple times, there are open issues already for it, and it is being worked on.

**Comment by navidmafi** [comment]
Can you link the issue/pr @guyroyse ?

**Comment by guyroyse** [comment]
#75 has a half-dozen or so of them.
