### ISSUE TITLE
Is there a way to use it with Upstash?

### ISSUE THREAD

**Issue by promentol** [redis/redis-om-node#134]
Upstash provides serverless Redis, working on top of Http.
They provide a library, which have same interface as regular Redis Client library
https://github.com/upstash/upstash-redis

How can I configure redis-om-node to work with upstash, e.g. replace Redis Client.

Thanks in advance

**Comment by promentol** [comment]
My apologies, seems `const client = await new Client().use(redis)` can be used to pass upstash Redis Client.

**Comment by guyroyse** [comment]
Yes. That will work. Do be aware that a lot of the functionality of Redis OM depends on RediSearch and RedisJSON. Upstash does not offer those modules as part of their service. So, you will be limited to basic CRUD operations against Hashes.

**Comment by ExProbitasFiducia** [comment]
It seems like upstash is supposed to support json now:
https://upstash.com/blog/redis-json

Though i am still having issues:

```
Error: ERR unknown command 'JSON.GET', with args beginning with: 'myschema:sayhello' '$'
```
