### ISSUE TITLE
Error on schema mistmatch after repository fetch

### ISSUE THREAD

**Issue by tnkarno** [redis/redis-om-node#135]
Hi, I just found a problem in my project which uses the redis-om-node package. My redis database changes over time, and the schema also. Some entities contain extra fields which fields are not defined in the schema. If I do a fetch on these objects the OM throws an error.  The error comes from this line, I think the OM tries to fetch the field from the schema, I think there should have been some checks, or I missed some configurations.
Error:
![image](https://user-images.githubusercontent.com/77674271/192989698-2ff9e0eb-69c7-423e-97a7-781f2c60083a.png)
The error comes from here:
![image](https://user-images.githubusercontent.com/77674271/192989941-6dda6490-fbae-4467-b8e9-3ab356b8a9b5.png)

Version: 0.3.6

**Comment by guyroyse** [comment]
So you have fields in Redis that aren't defined in your schema? That would certainly create an error. This will be resolved in version 1.0 but in the meantime, can you add the missing fields to your schema? Redis OM for Node.js can handle missing fields in the data just fine but not missing fields in the schema.

**Comment by tnkarno** [comment]
It depends on when you wanna release the 1.0 because this will be a lot of maintenance.

**Comment by guyroyse** [comment]
This was fixed with the release of Redis OM 0.4.0 Beta. Install it with `npm install redis-om@beta`.
