### ISSUE TITLE
Feature: "in" query clause functionality

### ISSUE THREAD

**Issue by vgjenks** [redis/redis-om-node#141]
Would be great if an "in" filter could be applied to a query like so:

`data.and("first_name").in(["Larry", "Curly", "Moe"]);`

...vs using a loop/map/whatever:

```
names.forEach(name => {
    data.or("first_name").eq(name);
});
```

**Comment by guyroyse** [comment]
This is a duplicate of #44 so I'm gonna go ahead and close it.
