### ISSUE TITLE
Is it possible to save nested json?

### ISSUE THREAD

**Issue by JYeop** [redis/redis-om-node#151]
Like the title, i tried to save json with this package like below.

```ts

const roomEntity = roomRepository.createEntity({
          readAt: [{ cccccc: 0 }],
        })

```

but the result:
<img width="203" alt="image" src="https://user-images.githubusercontent.com/17217621/209737766-34a3d247-86c2-4f3d-9511-0d13b35b6f48.png">

So far, i only can think of saving with JSON.stringify + string type in schema like the img below.
<img width="193" alt="image" src="https://user-images.githubusercontent.com/17217621/209737897-1ee0cd70-157e-4755-bbca-cf39d96d65b3.png">

Is there any way to save raw json?

**Comment by guyroyse** [comment]
This has been requested many times and there are probably half a dozen issues mentioning it. It is currently under development and I plan to have it published on npm by the end of the month.

**Comment by JYeop** [comment]
Is there any progress?

**Comment by SwapnilSoni1999** [comment]
Here for the update :')

**Comment by guyroyse** [comment]
Code review is complete. Found an issue that I am addressing—not a huge problem. All goes well I'll cut a release this week. Monday at the latest.

**Comment by guyroyse** [comment]
Also, all the work that I've been doing on this is in the release-0.4.0 branch if you want a sneak peek.

**Comment by SwapnilSoni1999** [comment]
AWESOME!

**Comment by guyroyse** [comment]
I cut a beta release. Go and check it out at NPM. https://www.npmjs.com/package/redis-om/v/0.4.0-beta.1

**Comment by guyroyse** [comment]
Be aware that there are breaking changes that affect all users. Read the README. Read the CHANGELOG.
