### ISSUE TITLE
Clarify README for reds-om-node requirements

### ISSUE THREAD

**Issue by strefethen** [redis/redis-om-node#152]
I'm looking at this package for use in my application but I could use some clarification of the requirements in the README which states (emphasis mine):

>Of course, you'll need **some** Redis, preferably [Redis Stack](https://redis.io/docs/stack/) as it comes with [RediSearch](https://oss.redis.com/redisearch/) and [RedisJSON](https://oss.redis.com/redisjson/) ready to go.

Does "some Redis" mean you can use this package without RediSearch and RedisJSON? Or are those hard requirements? 

Thanks

**Comment by guyroyse** [comment]
You can use it without RediSearch and RedisJSON but you'll only be able to use CRUD operations against Hashes. You won't be able to create an index, search, or use RedisJSON.
