### ISSUE TITLE
matchesExactly doesn't work on text with special chars .  - #

### ISSUE THREAD

**Issue by loicbisiere** [redis/redis-om-node#154]
If I defined a `combinedId` in my schema as `combinedId: { type: "text" }` and try to use `matchesExactly` on it, here are my result based on the format of my `combinedId`:

- `id1-id2` => matchesExactly found nothing
- `id1.id2` => matchesExactly found nothing
- `id1#id2` => matchesExactly found nothing
- `id1 id2` => matchesExactly work properly
- `id1id2` => matchesExactly work properly

Are the `-`, `.` and `#` char create some issues for `matchesExactly` search?

**Comment by guyroyse** [comment]
Sounds like a bug. I'll look into it.

**Comment by guyroyse** [comment]
Looked into this and answered it for another user. This is a feature, as the saying goes. ;) Here's the details:

https://github.com/redis/redis-om-node/issues/179
