### ISSUE TITLE
Is the README out of date?

### ISSUE THREAD

**Issue by vsarang** [redis/redis-om-node#160]
Trying to set redis up today but I've immediately been getting strange errors even though I'm following the README to a tee:

```js
import { EntityId } from 'redis-om'
```

```
'"redis-om"' has no exported member named 'EntityId'. Did you mean 'Entity'? (FixIt)
```

And another one:
```js
import { Repository } from 'redis-om'

const albumRepository = new Repository(albumSchema, redis)
```
```
Cannot create an instance of an abstract class.
```

Version:
```
redis-om@^0.3.6:
   version "0.3.6"
   resolved "https://registry.yarnpkg.com/redis-om/-/redis-om-0.3.6.tgz#5c2d9e57a614e2ae9c21b8ab1d22baa0b7c63fa6"
   integrity sha512-WRmrAm1n1EQIQbEwbfqpceuxHgr7LKOZ471c/KGxyOTVFFm53E0S7vFSZA7a1Jnga7aHTOYqLhhMWE0lKKdsNw==
   dependencies:
     redis "^4.0.4"
     ulid "^2.3.0"
```

**Comment by guyroyse** [comment]
The README is in agreement with the current _beta_ version for Redis OM for Node.js which I would heartily encourage you to check out.

**Comment by vsarang** [comment]
How do I get the beta version?

I simply followed the instructions in the README:
```
npm install redis-om
```
This gave me `redis-om@^0.3.6` which was throwing the errors I listed above when I tried to continue following the README instructions.

**Comment by guyroyse** [comment]
`npm install ***@***.***`

**Comment by vsarang** [comment]
So any hint on which version I'm supposed to install to get the "beta" version? Again, it's not listed anywhere in the README...

Maybe here? https://github.com/redis/redis-om-node/tags

Am I supposed to install v0.2.0 to get the beta?

Forgive me if I'm coming across as an idiot -- I'm really trying here dude! But it is kinda hard because _there is no documentation on any of this_.

**Comment by guyroyse** [comment]
Sorry. My phone decided to star out what I guess it thought was an email address.

Just do `npm install redis-om@beta`.

**Comment by vsarang** [comment]
Ah got it, thank you!

I opened a PR here to just include this tidbit in the README: https://github.com/redis/redis-om-node/pull/161

I'm happy to address feedback if you want it done in a different way. I'm sad that I'll have to redo some work to get on the beta version, and I'd like to save future devs the effort if possible.
