### ISSUE TITLE
Vector similarity

### ISSUE THREAD

**Issue by andregosling** [redis/redis-om-node#164]
Hello guys. I'm trying to use this feat: Vector similarity (https://redis.io/docs/stack/search/reference/vectors), that uses redisearch. 

At this repository of redisearch on github (https://github.com/RediSearch/RediSearch), i found that redis-om-node supports the use of redisSearch, but i wasn't able to find anything here related to this topic. 

How can i be able to compare vectors similarity saved into my redis db with another vector on my memore by cosine without querying all my data to memory and doing it on my code?

Thanks you all!

**Comment by guyroyse** [comment]
Redis OM does not yet support VSS. There's a PR and an issue for this already. See https://github.com/redis/redis-om-node/pull/104 and https://github.com/redis/redis-om-node/issues/153.
