### ISSUE TITLE
'Entity' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by argupta23** [redis/redis-om-node#170]
I am using 4.0-beta and am trying to create the below schema.

todo.schema.ts

```javascript
import { Schema, Entity } from "redis-om";

class Todo extends Entity { }
const todoSchema = new Schema(Todo, {
  name: { type: 'string' },
  description: { type: 'string' },
  createdAt: { type: 'date', sortable: true },
  done: { type: 'boolean' },
  favorited: { type: 'boolean' }
}, { dataStructure: 'JSON' });

export { Todo, todoSchema };

```

When I do that I get the following error. 

```html
import Entity
Defines the objects returned from calls to repositories .

'Entity' only refers to a type, but is being used as a value here.ts(2693)
```

If I rename the file to .js then the error seems to go away.

Can somebody please let me know how I can resolve the issue?

Thanks in advance.

**Comment by argupta23** [comment]
I took a second look at the Readme and it looks like in 4.0 we don't need to have the below line anymore.

```javascript
class Todo extends Entity { }
```
Is my assumption right?

**Comment by guyroyse** [comment]
That is correct. Entity is simply there for TypeScript now. It's not a _class_, just a type.

**Comment by argupta23** [comment]
@guyroyse 
Thanks for the prompt response and confirmation.
