### ISSUE TITLE
Add example in Readme for "path" with nested  array of objects

### ISSUE THREAD

**Issue by argupta23** [redis/redis-om-node#171]
Can somebody please point me as to how one would create a schema using path with nested array of objects?

However, you might not want your JavaScript object and your JSON to map this way. So, you can provide a path option in your schema that contains a [JSONPath](https://redis.io/docs/stack/json/path/#jsonpath-syntax) pointing to where that field actually exists in the JSON and your entity. For example, we might want to store some of the album's data inside of an album property like this:

```javascript
{
  "album": {
    "artist": "Mushroomhead",
    "title": "The Righteous & The Butterfly",
    "year": 2014,
    "genres": [ "metal" ]
  },
  "outOfPublication": true
}
```
To do this, we'll need to specify the path property for the nested fields in the schema:

```javascript
const albumSchema = new Schema('album', {
  artist: { type: 'string', path: '$.album.artist' },
  title: { type: 'string', path: '$.album.title' },
  year: { type: 'number', path: '$.album.year' },
  genres: { type: 'string[]', path: '$.album.genres[*]' },
  outOfPublication: { type: 'boolean' }
})
```

If we extend the example to look like below
```javascript
[
{
  "album": {
    "artist": "Mushroomhead",
    "title": "The Righteous & The Butterfly",
    "year": 2014,
    "genres": [ 
        { "type": "x1", "price": "2.00" },
        { "type": "x2", "price": "3.00" },
        { "type": "x3", "price": "4.00" },
     ]
  },
  "outOfPublication": true
}
.......
]

```

what would be equivalent of this line where "genres" is now an array of objects vs string?
 
```javascript
  genres: { type: 'string[]', path: '$.album.genres[*]' },
})
```
Additionally can we add the example to the Readme as well?

Thanks in advance.

**Comment by guyroyse** [comment]
Like this: `$.album.genres[*].type`.

This is just one of many things that JSONPath can do. For example, you could get all the root properties and treat them as an array as well using `$.*`. Assuming this returned all strings, Redis OM would be happy with it.

Regarding updating the README for this case, I can see some utility in it but I don't think I'd want to go much further than that as I don't want to duplicate a bunch of existing JSONPath documentation. I think I have a link to JSONPath already but I'm not 100% sure. If not, I need to add it.

**Comment by argupta23** [comment]
@guyroyse 
Sorry I missed the linkage to JSONPATH in the Readme. I will do some more reading on it.

I want to make sure I understand your response right, in this case my schema would then look like

```javascript
genres: { type: 'string[]', path: '$.album.genres[*].type'},
genres: { type: 'number[]', path: '$.album.genres[*].price'},
})
```

would        "genres: { type: 'string[]',"                  still be the case for array of objects?

Thanks, looking forward to your response.

**Comment by guyroyse** [comment]
Correct. `genres` would still be a `string[]`. The type needs to match what the JSONPath query will return.

Redis OM doesn't support searching and indexing on arrays of numbers. You can still store them and get them back, but you can't index them or search on them. The schema is primarily about that indexing and searching so if you are just storing them, you can safely remove the schema entry.

**Comment by argupta23** [comment]
@guyroyse 
Thanks. I will give a try.

**Comment by argupta23** [comment]
@guyroyse 
One additional question
How do you setup the schema when you don't know the contents of the nested object?

**Comment by thienantran010** [comment]
`
genres: { type: 'string[]', path: '$.album.genres[*].type'},
genres: { type: 'string[]', path: '$.album.genres[*].price'},
})
`
So based on this example, listing a field multiple times doesn't overwrite the path or type? genres can have two paths? Also, would the following schema fragment result in the same thing?
`
type : {type: 'string[]', path: '$.album.genres[*].type'},
price: {type: 'string[]', path: '$.album.genres[*].price'}
`
