### ISSUE TITLE
I can get .equals to work, but not .matches

### ISSUE THREAD

**Issue by vrghost242** [redis/redis-om-node#175]
I've been trying to figure this out, and I have a entry (among 23K) on redis Enterprise that looks like

`{
id:"2"
elementName:"Garlic"
elementType:"powder"
elementCarbonFactor:"0.74941"
carbonFactorSource:"Agribalyse"
unit:"kg"
geography:"FRA"
}`

And if I do the search below, it works perfectly:

```
        console.time("Redis Search time");
        await repository.createIndex().catch((err) => {
          console.log("Error creating index");
          console.log(err);
        });
        let response =await repository.search()
          .where('elementName') // search for the field
          .equals("Garlic") // search for the value
          .return.all(); // return all the results
        console.log(response[0].elementName);
```
        
     However, if I change the above to match entires containing Garlic instead using **.matches** I get "Process finished with exit code 1" but no error message anywhere as far as I can see
```
        let response =await repository.search()
          .where('elementName') // search for the field
          .matches("Garlic") // search for the value
          .return.all(); // return all the results
        console.log(response[0].elementName);
```

Any help would be greatly appreciated

**Comment by guyroyse** [comment]
`.equals` is for fields of type `string`, `number`, and the like but not `text` fields. `.matches` is exclusively for `text` fields.

Probably related to that. What does you Schema look like?

**Comment by vrghost242** [comment]
const envStatSchema = new Schema(EnvStat, {
  id: { type: 'string' },
  elementName: { type: 'string' },
  elementType: { type: 'string' },
  elementCarbonFactor: { type: 'string' },
  carbonFactorSource: { type: 'string' },
  unit: { type: 'string' },
  geography: { type: 'string' },
});

So maybe this is a support question then :) 

How do I do a partial match on a string? So that Garlic would match say Garlic Powder

**Comment by guyroyse** [comment]
I know with the Beta you can just throw an asterisk at the end of your call to `.equals`. Not sure if this will work with the current non-beta version. I think it might try to escape it. Not at a computer right now to be able to test it.

**Comment by vrghost242** [comment]
Thank you so very much by the way, by switching it to text and using matches it worked perfectly
