### ISSUE TITLE
redis-om language options parity

### ISSUE THREAD

**Issue by ababich** [redis/redis-om-node#178]
copy of https://github.com/redis/redis-om-python/issues/502

Hello! how can I fing if different redis-om implementations are compatible (mostly I'm interested in python vs node/TS)

how much compatible, etc. May be there is any table or notes for that?

Sample use case: I want to use same redis DB with lambdas implemented in different languages and I want to make sure any modifications, migrations, etc. would not ruin experience for another platform

Thank you!

**Comment by guyroyse** [comment]
They are no guarantees of compatibility between languages of Redis OM. When we wrote the various versions, we decided not to do this as it was and edge case and would greatly complicate the development effort.

**Comment by ababich** [comment]
Thank you for the clarification
