### ISSUE TITLE
Loading empty `string[]` field type

### ISSUE THREAD

**Issue by jhmaster2000** [redis/redis-om-node#180]
I have a `string[]` typed field in my redis-om schema, and the arrays can vary in length, including 0.

However I am facing an issue where saving an entity with the field set to `[]` will work fine, but when loading the entity back, it gets loaded as `[""]`, with an empty string in the place of the 1st index.

This completely disrupts all kinds of array length based checks such as `if (entity.array.length === 0)` and introduces nasty silent bugs, especially since as far as I can see this is not documented anywhere if it is intended behavior for whatever reason.

So could this either be fixed, or if its intentional, explained why and documented somewhere common so it doesn't catch people off-guard at least?

**Extra details:**
I am using redis-om 0.4.0-beta.3 on Node.js 19.9.0 with HASH schemas (my Redis instance does not have modules)

**Comment by guyroyse** [comment]
Sounds like a bug. I’ll look into early next week.

**Comment by guyroyse** [comment]
Also, thanks for the extra detail. I’m 90% sure I know what the problem is.

**Comment by guyroyse** [comment]
This hasn't fallen off my radar. I've been on the road for the last five weeks. Should have time early next week when I'm in Oslo to work on this. Thanks for you patience.
