### ISSUE TITLE
Argument of type 'string' is not assignable to parameter of type 'EntityConstructor '.

### ISSUE THREAD

**Issue by yuzhanglong** [redis/redis-om-node#182]
the example in README fails to pass TypeScript check.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/56540811/236655243-23a9c82b-7d0c-48dd-afed-6a2dab099e13.png">

**Comment by guyroyse** [comment]
Sounds like you have installed Redis OM 0.3.x. The current README is for the *beta* version of 0.4.1 which has breaking changes from 0.3.x. This is noted near the top of the README in the [Getting Started](https://github.com/redis/redis-om-node#getting-started) section.

**Comment by yuzhanglong** [comment]
> Sounds like you have installed Redis OM 0.3.x. The current README is for the _beta_ version of 0.4.1 which has breaking changes from 0.3.x. This is noted near the top of the README in the [Getting Started](https://github.com/redis/redis-om-node#getting-started) section.

thanks!
