### ISSUE TITLE
Feature: fuzzy search

### ISSUE THREAD

**Issue by Neeraj-Ghodla** [redis/redis-om-node#196]
Can we add fuzzy search support in Full-Text search?

We could modify the match function to something like

```js
albumRepository
  .search()
  .where('title')
  .match('buterfly', { fuzzy: true, levenshteinDistance: 1 })
```

NB: Typo on buterly is delibrate

**Comment by guyroyse** [comment]
This is a good idea. I'll mark it as an enhancement.

**Comment by Neeraj-Ghodla** [comment]
@guyroyse I've created a [PR](https://github.com/redis/redis-om-node/pull/200) to add support for fuzzy matching.

**Comment by fabiel-leon** [comment]
how can i fuzzy search in all fields ? 
a query like this ```FT.SEARCH index "%word%"```

**Comment by guyroyse** [comment]
If you want to do more advanced searches you can always use the `. searchRaw` method. A simple example is in the [README](https://github.com/redis/redis-om-node/#running-raw-searches).
