### ISSUE TITLE
Fetch expiry time of a key

### ISSUE THREAD

**Issue by sarangBuzzyBrains** [redis/redis-om-node#203]
Hi all, Is there anyway of fetching expire time of a particular key ? 
The below method only shows entityId and schema fields.
`repository.search().where('orgId').equals(orgId).return.all();`

I also checked the code and did not found any method which return expiry time of existing fields, can anyone please assist me over this thank you.

**Comment by guyroyse** [comment]
You can call `.ttl` on the Node Redis connection to get this. The key name is a property on the returned Entity. You can access it with a Symbol, just like with the EntityId. Here's a simple example.

```javascript
import { EntityKeyName } from redis-om

const someEntity = await someRepository.fetch('12345')
const key = someEntity[EntityKeyName]
const ttl = await redis.ttl(key)
```

This example assumes you have a Redis connection named `redis`.
