### ISSUE TITLE
cannot read properties of undefined (reading 'set')

### ISSUE THREAD

**Issue by F-Y-M** [redis/redis-om-node#210]
OS: WINDOWS 10 22H2
NODE: 18.16.1
REDIS: redis:6.2.13-alpine3.18 
DOCKER: V4.22.0

issue: i having this error when i try to create some users. i have this schema for the users:
C:\Users\USER\Documents\proyects\express-redis-om-workshop\node_modules\redis-om\dist\index.js:1754
    await this.redis.json.set(key, "$", data);
                          ^

TypeError: Cannot read properties of undefined (reading 'set')
    at Client.jsonset (C:\Users\taiyoukou\Documents\proyects\express-redis-om-workshop\node_modules\redis-om\dist\index.js:1754:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Repository.writeEntityToJson (C:\Users\taiyoukou\Documents\proyects\express-redis-om-workshop\node_modules\redis-om\dist\index.js:1655:5)      

Node.js v18.16.1

SERVER
````
import 'dotenv/config'

import express from 'express'
import swaggerUi from 'swagger-ui-express'
import YAML from 'yamljs'

/* import routers */
import { router as personRouter } from './routers/person-router.js'

/* create an express app and use JSON */
const app = new express()
app.use(express.json())

/* bring in some routers */
app.use('/person', personRouter)

/* set up swagger in the root */
const swaggerDocument = YAML.load('api.yaml')
app.use('/', swaggerUi.serve, swaggerUi.setup(swaggerDocument))

/* start the server */
app.listen(8080)
````

CLIENT
````
import { createClient } from 'redis'

const url = process.env.REDIS_URL
const client = await new createClient({url})

client.on('error', error => {
    console.log("#ESTO OCURRIO: ", error)
})

export default client.connect()
````

PERSON
```
`import pkg from 'redis-om'
const { Repository, Schema } = pkg

// console.log("pkg, ", pkg)

import client from './client.js'

// class Person extends EntityId {}

const  PersonSchema = new Schema('Person', {
    firstName: { type: 'string'},
    lastName: { type: 'string'},
    age: { type: 'number'},
    varified: { type: 'boolean' },
    location: { type: 'point' },
    locationUpdated: { type: 'date' },
    // skills: { type: 'string[]' },
    personalStatement: { type: 'text' }
})

export const PersonRepository = new Repository(PersonSchema, client)
````

PERSON-ROUTER
```
`import { Router } from 'express'

import { PersonRepository } from '../om/person.js'

export const router = Router()

// CREATE
router.put('/', async (req, res) => {
    console.log("AGREGANDO UN USUARIO")
    const person = await PersonRepository.save(req.body)
    res.send(person)
})

// READ
router.get('/:id', async (req, res) => {})

// UPDATE
router.post('/:id', async (req, res) => {})

// DELETE
router.delete('/:id', async (req, res) => {})
````

steps for reproduce the issue: 
1- install redis and redis-om
2- create a server with express
3- create some routes
4- create the schema and the redis-client
5- try to create on user

i don't know if is a issue with the package or the manner that i do the schema. thanks for your help

**Comment by guyroyse** [comment]
Redis OM requires the use of Redis' Search and JSON features to function. This looks like either the version of Node Redis you are using doesn't support JSON or the version of Redis itself that you are using does not. Seeing how you have a docker image of `redis:6.2.13-alpine3.18`, this is probably your problem as this image does not include JSON and Search.

However, you error suggests that you don't have the correct version of Node Redis. So, I'll address both:

- For the version of Node Redis, a straight up `npm install redis` should do the trick. The latest version is 4.6, I think. Make sure you have the latest and you should be good.

- For the Redis image, the easiest way to get a version of Redis that has Search and JSON in it would be to install Redis Stack. Version 7.2 is out today, actually, if you want to play with that. Just a quick `docker run` away:

```bash
docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:7.2.0-v0
```

Let me know if this fixes you issues and then we can close this out.

Thanks!

**Comment by F-Y-M** [comment]
> Redis OM requires the use of Redis' Search and JSON features to function. This looks like either the version of Node Redis you are using doesn't support JSON or the version of Redis itself that you are using does not. Seeing how you have a docker image of `redis:6.2.13-alpine3.18`, this is probably your problem as this image does not include JSON and Search.
> 
> However, you error suggests that you don't have the correct version of Node Redis. So, I'll address both:
> 
> * For the version of Node Redis, a straight up `npm install redis` should do the trick. The latest version is 4.6, I think. Make sure you have the latest and you should be good.
> * For the Redis image, the easiest way to get a version of Redis that has Search and JSON in it would be to install Redis Stack. Version 7.2 is out today, actually, if you want to play with that. Just a quick `docker run` away:
> 
> ```shell
> docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:7.2.0-v0
> ```
> 
> Let me know if this fixes you issues and then we can close this out.
> 
> Thanks!

really thanks for ur help is a honor to me. 
° for the version of redis: i install redis again but not works
° for the docker image: i download this image and really works thanks a lot

**Comment by guyroyse** [comment]
Sounds like you're good. I'll close the issue. Thanks for using my stuff!
