### ISSUE TITLE
Improved error handling when opening the Client

### ISSUE THREAD

**Issue by codediodeio** [redis/redis-om-node#22]
When opening the client, it will throw an error if an existing client is open. 

https://github.com/redis/redis-om-node/blob/bded9858c83708c4e847ad74709b454549ca998d/lib/client.ts#L61

It may be better if this error is removed or just logged as a warning. OR the client should implement a public boolean property like is `isOpen` so the end user can do a check at runtime. Currently, it seems impossible to know if the client is open or not.

**Comment by lucemans** [comment]
👀

**Comment by guyroyse** [comment]
Merged this into dev. Will push a new version to npm tomorrow.

**Comment by guyroyse** [comment]
Pushed to npm, should be good to go.
