### ISSUE TITLE
Make Repository a generic class / infer Entity from Schema

### ISSUE THREAD

**Issue by jonahschueller** [redis/redis-om-node#227]
It seems like the current version of `redis-om` does not have any support for a custom repository entity type. Apparently, the `Entity` type is hard coded into the `Repository` class (correct me if I am wrong). 

I think this is a good point to introduce some Typescript Generics support.

I am thinking of something like this:
```typescript
interface Person extends Entity {
   name: string
   age: number
}

const PersonSchema = new Schema(...)

const personRepo = new Repository<Person>(PersonSchema, client)
```

With this approach, the `save`, `fetch`, ... functions of the repository would give proper IntelliSense.

I assume the changes wouldn't be too much. Something like:
```typescript

class Repository<E extends Entity = Entity> {

   async save(entity: E)

   ...

}
```
---

A more advanced approach would be to infer the resulting entity type from the Schema definition. However, this would need a lot of refactoring of the type definitions.

**Comment by Eji4h** [comment]
I had the same issue.

**Comment by AlaaZorkane** [comment]
Seems like a no brainer, I don't know why this wasn't implemented on the first place. +1

**Comment by Wato1818** [comment]
It would be very useful. But i feel the improvement may be way more complex than we think. +1

**Comment by dennisofficial** [comment]
I feel like this should be the norm. TypeScript is for strict typing, I can't type an `Entity`

**Comment by ricardovf** [comment]
+1

**Comment by dennisofficial** [comment]
I just remembered about this issue. It should be closed since the PR above allows stricter typing.

**Comment by jonahschueller** [comment]
@dennisofficial Thank you very much for this contribution! I will close this issue.
