### ISSUE TITLE
problem when storing JSON.stringify(an object) into redis

### ISSUE THREAD

**Issue by luxdo** [redis/redis-om-node#253]
I'm writing to share a peculiar observation I've encountered while using Redis Insight to inspect data stored in my Redis database, specifically JSON data. I've noticed that, at times, Redis Insight displays the stored JSON.stringify(an object) in an expandable format, allowing for easy navigation and inspection of the object's properties. However, in other instances, the same JSON data is displayed as a plain string, without any expansion or formatting.
like
```
productsRepository.save({
   details: JSON.stringify({stockId: "#98105", price: 35})
})
```

I'm curious to know if this behavior is intentional or if there might be a specific configuration or data structure that could be influencing this inconsistency. It would be incredibly helpful to have a consistent display format for JSON data, especially when dealing with complex objects.

I've attached a screenshot to illustrate the two different display modes. I think there is a problem 
![redis-serialization-error](https://github.com/user-attachments/assets/00a48333-fb10-4dc5-9e05-567094942169)
![redis-object](https://github.com/user-attachments/assets/5d14b65d-a57c-4923-bcb0-2369729b3f8c)
with serialization 

Thank you for your time and consideration. I look forward to your insights.

**Comment by guyroyse** [comment]
If you call `JSON.stringify`, it will turn the JavaScript object into a string. Storing that string in Redis OM will, well, store it as a string. Redis OM does not attempt to figure out if strings contain JSON or not. If you give it a string, it will treat it as a string.

You probably want to call `.save` like this:

```javascript
productsRepository.save({
  details: {
    stockId: "#98105",
    price: 35
  }
})
```

**Comment by luxdo** [comment]
Yeah, 
As a point of comparison, I've tested the same operations using the direct Redis client and everything works fine. This suggests that there might be underlying problem within the Redis-OM library.
give it a shot
```
const sampleProduct = {
 stockId: '#123',
 name: 'sample product',
 details: { for: 3, unit: 'month' },
 status: 'active'
 };
 await client.json.set(`products:${sampleProduct.pid}`, '$', sampleProduct); // works fine
 const redisOmProduct = await productsRepository.save(sampleProduct); // error, Unexpected value for field 'details' of type 'string' in JSON at '$["details"]'
const redisOmProduct = await productsRepository.save(JSON.stringify(sampleProduct)) // serialization problem in Redis Insight, could not be detected as a JSON object like the direct client.json.set() call
```

**Comment by luxdo** [comment]
I wanted to clarify my understanding of the discussion we had regarding nested objects and Redis-OM.

Based on our conversation, it seems that Redis-OM doesn't currently support nested objects with an arbitrary number of members or names. Is that correct?

I believe might have a solution to the nested object limitation.
It seems that by omitting the specific object type definition within the Redis-OM schema, we can achieve the desired flexibility of nesting objects to arbitrary depths. This approach allows for dynamic structures without the need to predefine a rigid schema. (removing details: {type: 'string', path: '' …} in schema)

```
	const redisOmProduct = await productsRepository.save({
		stockId: '#12499999',
		name: 'sample product 2',
		details: {  // works perfectly fine when there is no defined "details" type in schema.
			quantity: 10,
			unit: 'device'
		}
	});
```

Could you please confirm if this interpretation is accurate? Your expertise would be invaluable in validating this solution.
Thank you for your time and assistance.

**Comment by guyroyse** [comment]
Yes. That is accurate and by design. A Schema only needs to contain fields you want to search on or perform type coercion on. If you don't want to those things, there's no need to specify them.
