### ISSUE TITLE
reuturn.page problem

### ISSUE THREAD

**Issue by luxdo** [redis/redis-om-node#255]
Hi,

I'm writing to report a potential bug I encountered while using the Redis-OM library for pagination.

I understand there's a limitation of returning a maximum of 10,000 records with the .return.all() function. However, I'm facing an issue with the .return.page(offset, count) function designed for pagination.

According to the documentation, .return.page(offset, count) should return count number of records starting from the offset position. However, in my testing, the function seems to be limited to returning a maximum of (10,000 - offset) records. In other words, it appears the total number of returned records is capped by the difference between 10,000 and the provided offset, rather than the specified count value.

For example, if I have a dataset of 15,000 records and call .return.page(8000, 3000), I would expect to receive 3000 records starting from the 8000th record. However, based on my observations, the function might only return (10,000 - 8000) = 2000 records.
```javascript
const result = ordersRepository.search().where('isPaid').equals(true).return.page(8000, 3000); 
console.log(result.length) // returns 2000 while having more than 15000
```

Could you please confirm if this behavior is intended or if it might be a bug?  If it's a bug, I'd be happy to provide any additional information or code samples to help with further investigation.

Thank you for your time and consideration.

**Comment by guyroyse** [comment]
This is a result of how Redis Query Engine works. Any search will return a max of the first 10,000 matches. A pagination doesn’t change this. It just lets you paginate through this first 10,000.

The limit of 10,000 can be changed in the search configuration on your Redis instance. I’m on my phone in an airport right now so I can’t provide a link, but I know it’s documented on redis.io somewhere.

**Comment by guyroyse** [comment]
Here's the [relevant documentation](https://redis.io/docs/latest/develop/interact/search-and-query/basic-constructs/configuration-parameters/) for search's configuration settings.
