### ISSUE TITLE
Add support for embedded schemas

### ISSUE THREAD

**Issue by lukeribchester** [redis/redis-om-node#30]
It is not currently possible to embed/nest schema definitions.

This is implemented in the Python library (see [Embedded Models](https://github.com/redis/redis-om-python#embedded-models)).

Reference: [schema-definitions.ts#L59](https://github.com/redis/redis-om-node/blob/f6743b4a7403fc1d76e804cb9058c72295cedd2a/lib/schema/schema-definitions.ts#L59)

Thank you.

**Comment by navneet1v** [comment]
Waiting for this feature to come. Really need this feature badly. I don't want to switch to using plain redis client in my next.js project.

**Comment by JannisHajda** [comment]
Same here - desperately waiting for that features, since it is already available in the python library.

**Comment by lukeribchester** [comment]
@guyroyse what priority does this have on the roadmap? I can possibly contribute this in April.

**Comment by guyroyse** [comment]
Right after sorting.

**Comment by guyroyse** [comment]
This was fixed with the release of Redis OM 0.4.0 Beta. Install it with `npm install redis-om@beta`.
