### ISSUE TITLE
How does Repository#save work?

### ISSUE THREAD

**Issue by nordiauwu** [redis/redis-om-node#31]
It is stated in the docs that `You also use .save to update an existing entity`, but how does it know if there is an existing entity?

**Comment by guyroyse** [comment]
It doesn't. Redis (and by extension) Redis OM always does upserts.

**Comment by nordiauwu** [comment]
So to update, for example, a user whose email (but not id) is known I have to search for that user first and save it afterward, and there is no way to do it in a single query, right?

**Comment by guyroyse** [comment]
Correct.

**Comment by nordiauwu** [comment]
Thanks
