### ISSUE TITLE
 repository.search(...).where(...).eq is not a function

### ISSUE THREAD

**Issue by ferdigokdemir** [redis/redis-om-node#33]
My Code:
`const item = await repository.search().where('code').eq(i.code).return.all();`

`"redis-om": "^0.1.7"`

What is wrong?

**Comment by guyroyse** [comment]
`.eq()` isn't implemented for every field type. What type of field is "code" in your schema?

**Comment by danipatko** [comment]
I had the same issue. As far as i know, `.eq()` is only implemented for boolean number and string fields. The string field is a bit tricky because if you have `textSearch` enabled in your schema for that field, you won't be able to use the `.eq()` function, but `.matches()` instead.

**Comment by ferdigokdemir** [comment]
"code" type is string
