### ISSUE TITLE
Define own entityId

### ISSUE THREAD

**Issue by Lionardo** [redis/redis-om-node#40]
### Awesome package this is! ❤

**Is there a way to define an own entityId?**

I see there is a methode ```generateId()```
that is automatically called on Schema construction.

I would like to pass an existing generated id from an auth service or something similar.

**Comment by jamesastound** [comment]
There is.

```JAVASCRIPT
  class MySchema extends Schema {
    generateId() {
      return myIDGeneratorFunc(); // <<<
    }
  }
```

**Comment by guyroyse** [comment]
Actually, there is a configuration option when you create your schema to override the ID generation. It's documented here: https://github.com/redis/redis-om-node/blob/main/docs/README.md#schemaoptions.

The tl;dr:

```javascript
let schema = new Schema(SomeEntity, {
  foo: { type: 'string' },
  bar: { type: 'number' }
}, {
  idStrategy: myIDGeneratorFunc
})
```

**Comment by jamesastound** [comment]
That's really cool. I have read the main Readme, but have yet to dive into all the extended docs.

**Comment by Lionardo** [comment]
Yes that did the job. I was only passing a string before.


```typescript
const idGen = (): string => "CHECK|123";
let schema = new Schema(
...
  {
    dataStructure: "JSON",
    idStrategy: idGen,
  }
);
```

**Comment by CaptainCodeman** [comment]
Just came across this, I want to assign my own ID so used the entity constructor like this:

```ts
const post = new Post(PostSchema, 'my-post', postData)
const id = await repository.save(post)
// id === 'my-post'
```

**Comment by brynbeaudry** [comment]
T

> Just came across this, I want to assign my own ID so used the entity constructor like this:
> 
> ```ts
> const post = new Post(PostSchema, 'my-post', postData)
> const id = await repository.save(post)
> // id === 'my-post'
> ```

This doesn't work, TypeError: Class constructor Entity cannot be invoked without 'new'
