### ISSUE TITLE
 TypeError: repository.search.where is not a function

### ISSUE THREAD

**Issue by Lionardo** [redis/redis-om-node#41]
```albums = await repository.search.where('artist').eq('Mushroomhead').return.all()```

invokes error: TypeError: repository.search.where is not a function

adding //@ts-ignore

doesn't help

**Comment by guyroyse** [comment]
`.search` is a function so you need to invoke it like this:

```javascript
let albums = await repository.search().where('artist').eq('Mushroomhead').return.all()
```

Is my example code on developer.redis.com incorrect?

**Comment by Lionardo** [comment]
README in the section **Searching on Whole Strings** it is incorrect
```albums = await repository.search.where('artist').eq('Mushroomhead').return.all()```
Still I am facing the issue...

**Comment by guyroyse** [comment]
Oh. Yeah. That's really wrong and I copy pasta'd it all over the place! Thanks for the find.

**Comment by guyroyse** [comment]
Has your error changed when you call `.search` as a function?

**Comment by Lionardo** [comment]
Sadly not.
When I use this line i get a response:

```typescript
checkExisting = await repository.search().return.all();
```
but if I use this then I get the error:

```typescript
checkExisting = await repository.search().where("email").eq("test@test.com").return.all();
 ```

**TypeError: repository.search(...).where(...).eq is not a function**

**Comment by guyroyse** [comment]
What's the schema look like for the `email` field?

**Comment by Lionardo** [comment]
```typescript
let schema = new Schema(
  User,
  {
    email: { type: "string", textSearch: true },
    uid: { type: "string" },
  },
  {
    dataStructure: "JSON",
  }
);
```

**Comment by guyroyse** [comment]
You can't do `.eq` against searchable text fields. You can only do full-text search using `.matches`.

https://github.com/redis/redis-om-node#full-text-search

**Comment by Lionardo** [comment]
Oh yes, that did it. Thank you so  much.
