### ISSUE TITLE
Optionally return raw JSON instead of entities

### ISSUE THREAD

**Issue by guyroyse** [redis/redis-om-node#57]
Entities are fine, but sometimes you just need to JSON. Do this as a JavaScript object as well as a JSON string to save on the call to `.stringify`.

**Comment by pogiii** [comment]
I get why it's needed, but how would you think it could work syntax-wise?
How would you chose to have the output in JSON instead of Entities or vice versa?

**Comment by pogiii** [comment]
after digging into the source code I feel people might be confused with .toJSON which converts to JSON, but does not stringifies it.

How about
```
repo.search().return.allStringify()
repo.search().return.firstStringify()
```

Or something the references a JSON string more?
