### ISSUE TITLE
Unique value for field

### ISSUE THREAD

**Issue by kamalkech** [redis/redis-om-node#64]
```
const schema = new Schema(MyEntity, {
  token: { type: 'string' },
  status: { type: 'boolean' },
  date_expire: { type: 'date' },
});
```

how can i specifie that token field is unique ?

**Comment by guyroyse** [comment]
You can't. That's not something that Redis OM does.

**Comment by kamalkech** [comment]
ah ok so i guess the solution is to fetch old items and look if this value already existing in x item and reject
