### ISSUE TITLE
.createIndex() required 1 parameters but got none?

### ISSUE THREAD

**Issue by pgamerx** [redis/redis-om-node#71]
Hi there, the documentation doesn't mention anything needed to be added to .createIndex() function and this is my code:
```ts
import RedisClient from '@node-redis/client/dist/lib/client';
import { Client } from 'redis-om'

let redisClient: Client;
(async () => {

    /* pulls the Redis URL from .env */
    const url = process.env.REDIS_URL

    /* create and open the Redis OM Client */
    const rc = new Client()



    const redisClient2 = await rc.open(url)

    await redisClient2.createIndex()
    
    redisClient = redisClient2

})();

export default redisClient
```

The error I get:
![Screenshot 2022-04-24 at 9 59 15 AM](https://user-images.githubusercontent.com/71639879/164956685-1902476f-4631-4112-9271-889cfe4f6c80.png)

**Comment by pgamerx** [comment]
I am stupid

**Comment by guyroyse** [comment]
No worries. Being a programming is that bipolar vacillation between thinking ourselves brilliant and thinking ourselves idiots. ;)

**Comment by pgamerx** [comment]
> No worries. Being a programming is that bipolar vacillation between thinking ourselves brilliant and thinking ourselves idiots. ;)

Truer words have never been spoken
