### ISSUE TITLE
RedisError: The query to RediSearch had a syntax error: "Syntax error at offset 9 near messagesPerWindow".

### ISSUE THREAD

**Issue by OmgImAlexis** [redis/redis-om-node#80]
> RedisError: The query to RediSearch had a syntax error: "Syntax error at offset 9 near messagesPerWindow".
This is often the result of using a stop word in the query. Either change the query to not use a stop word or change the stop words in the schema definition. You can check the RediSearch source for the default stop words at: https://github.com/RediSearch/RediSearch/blob/master/src/stopwords.h.

I'm getting the error above when searching for an entitiy where `levels.messagesPerWindow` is greater than or equal to `1`.

I looked through the stop words and I'm not sure what part of this is the issue. The only thing I can think of is that `a` is in the stop words list and I use it in `messages` but that seems unlikely.

This is the code I'm using.

```ts
import autoBind from 'auto-bind';
import { Entity, EntityData, Schema } from 'redis-om';
import { client } from '../../../common/redis.js';

export interface Member {
    id: string | null;
    guildId: string | null;
    'levels.xp': number | null;
    'levels.level': number | null;
    'levels.messagesPerWindow': number | null;
    'stats.messageCount': number | null;
    'stats.reactionCount': number | null;
    'stats.voiceMinutes': number | null;
}

export class Member extends Entity {
    constructor(schema: Schema<any>, id: string, data?: EntityData | undefined) {
        super(schema, id, data);
        autoBind(this);
    }

    /**
     * Deletes the member from the database
     */
    async delete() {
        await memberRepository.remove(this.entityId);
    }

    /**
     * Persists the member to the database
     */
    async save() {
        await memberRepository.save(this);
    }
};

export const memberSchema = new Schema(Member, {
    id: { type: 'number' },
    guildId: { type: 'number' },
    'levels.xp': { type: 'number' },
    'levels.level': { type: 'number' },
    'levels.messagesPerWindow': { type: 'number' },
    'stats.messageCount': { type: 'number' },
    'stats.reactionCount': { type: 'number' },
    'stats.voiceMinutes': { type: 'number' }
}, {
    dataStructure: 'HASH'
});

export const memberRepository = client.fetchRepository(memberSchema);

await memberRepository.createIndex();
```

The following is what throws the error.
If I try and do a search without the where clause it returns all members without any issue.

```js
const members = await memberRepository.search().where('levels.messagesPerWindow').greaterThan(1).return.all();
```

**Comment by CaptainCodeman** [comment]
It'd be useful to include the Redis Query being generated (the profiler in RedisInsight lets you capture it)

**Comment by guyroyse** [comment]
You can also get the query it is generating in code:

```javascript
const query = memberRepository.search().where('levels.messagesPerWindow').greaterThan(1).return.query
```

Seeing that would help immensely in troubleshooting this issue.

**Comment by guyroyse** [comment]
I think we resolved this on the Discord server.

**Comment by waleedf112** [comment]
> I think we resolved this on the Discord server.

how? I'm facing a similar issue:
https://github.com/redis/redis-om-node/issues/130
